import './styles/globals.css';
import Head from 'next/head';
import { useEffect } from 'react';
import { GlobalStyles, theme } from '../styles/GlobalStyles';
import { MuiThemeProvider } from '@material-ui/core';
import { ThemeProvider } from 'styled-components';

function MyApp({ Component, pageProps }) {
    useEffect(() => {
        // Remove the server-side injected CSS.
        const jssStyles = document.querySelector('#jss-server-side');
        if (jssStyles) {
            jssStyles.parentElement.removeChild(jssStyles);
        }
    }, []);

    return (
        <>
            <Head>
                <title>Kss BPM</title>
                <meta name="viewport" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MuiThemeProvider theme={theme}>
                <ThemeProvider theme={theme}>
                    <GlobalStyles />
                    <Component {...pageProps} />
                </ThemeProvider>
            </MuiThemeProvider>
        </>
    );
}

export default MyApp;
